Adding a page that explains a bit the Batch Explorer as a tool.
hermeznetwork/docs pull request #24
Opened 2020-12-01 14:34 UTC by mmilenkovic

2020-12-01 18:55 UTC, druiz0992 requested changes
I think test is fine, but some pictures would greatly help to clarify. Is it possible to embed some captures of the block explorer?

Another thing: I did not see this page linked to _sidebar.md. I would just add it after SDK and API inside the developers section.  I would postpone the creation of a new Tools section until we have published the wallet and other tools. Otherwise it is a bit poor (this is just an opinion, and I am fine either way).

2020-12-02 07:57 UTC, jleebee commented on docs/tools/batch-explorer.md
> +* hez Ethereum address
HEZ Ethereum address

2020-12-02 08:31 UTC, mmilenkovic commented on docs/tools/batch-explorer.md
> +* hez Ethereum address
Done.

2020-12-02 12:40 UTC, davidsrz submitted a review, later dismissed

2020-12-03 18:14 UTC, druiz0992 approved these changes
Thanks

2020-12-03 18:40 UTC, merged

2020-12-03 18:40 UTC, druiz0992 commented
Already reviewed by three people