update dev guide
hermeznetwork/docs pull request #25
Opened 2020-12-01 17:34 UTC by invocamanman

Update and fix some lines of the dev guide

2020-12-01 20:11 UTC, druiz0992 commented on docs/developers/dev-guide.md
> +The coordinators are obliged to process L1 user transactions periodically. The smart contract establishes a deadline for the L1L2-batches. This deadline indicates the maximum time between two consecu
Coordinators must process L1 user transactions periodically.

2020-12-01 20:12 UTC, druiz0992 requested changes
Thanks for the review

2020-12-02 10:11 UTC, invocamanman commented on docs/developers/dev-guide.md
> +The coordinators are obliged to process L1 user transactions periodically. The smart contract establishes a deadline for the L1L2-batches. This deadline indicates the maximum time between two consecu
fixed!

2020-12-02 20:30 UTC, druiz0992 approved these changes, later dismissed

2020-12-16 07:20 UTC, krlosMata requested changes

2020-12-16 07:20 UTC, krlosMata commented on docs/developers/dev-guide.md
> +withdrawn by the governance under the tutelage of a emergency council that will return the funds to the users.
```suggestion
withdrawn by the governance under the tutelage of an emergency council that will return the funds to the users. 
```

2020-12-16 07:20 UTC, krlosMata commented on docs/developers/dev-guide.md
>  - Only the governance can add new tokens.
This has been changed. Anyone can add tokens.

2020-12-16 07:35 UTC, krlosMata approved these changes
:smile_cat:

2020-12-16 07:41 UTC, druiz0992 approved these changes

2020-12-16 08:48 UTC, jleebee requested changes
Change to a capital "E" for "ethereum"

2020-12-16 08:48 UTC, jleebee commented on docs/developers/dev-guide.md
> -- There cannot be two tokens with the same ethereum address.
Ethereum

2020-12-16 09:56 UTC, jleebee approved these changes

2020-12-16 09:57 UTC, merged