Update value-proposition.md
hermeznetwork/docs pull request #27
Opened 2020-12-11 16:07 UTC by jleebee

Final english and conventions revision :)

2020-12-12 10:13 UTC, davidsrz submitted a review, later dismissed

2020-12-13 18:55 UTC, druiz0992 commented on docs/about/value-proposition.md
Remove blank line

2020-12-13 18:56 UTC, druiz0992 requested changes
Small change requested.

Regards

2020-12-14 08:52 UTC, jleebee reviewed
Requested edits have been made, thanks!

2020-12-15 23:20 UTC, druiz0992 commented on docs/about/value-proposition.md
Can you remove extra line between Production Ready solution section and Decentralized?

2020-12-16 07:43 UTC, druiz0992 approved these changes

2020-12-16 07:44 UTC, druiz0992 commented
DavidS already approved previous version.

2020-12-16 07:45 UTC, merged