improve chainID explanation
hermeznetwork/docs pull request #37
Opened 2020-12-18 17:36 UTC by invocamanman

improve chainID explanation for TOB audit!

2020-12-18 17:41 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/protocol.md
> +- `chainId`: ethereum chain identifier in order to prevent replay attacks in case of hardforks, we use only 2 bytes because according to EIP-155, v is used to set the CHAIN_ID according to this formu
"Ethereum"

2020-12-18 17:42 UTC, jleebee requested changes
Just add a quick capital E to "ethereum", the rest looks great!

2020-12-19 16:30 UTC, krlosMata commented
> Just add a quick capital E to "ethereum", the rest looks great!

fixed!

2020-12-19 16:38 UTC, krlosMata submitted a review, later dismissed
:smile_cat:

2020-12-19 16:52 UTC, eduadiez approved these changes
LGTM

2020-12-19 16:53 UTC, jleebee approved these changes

2020-12-19 16:55 UTC, merged