Adds docs for wallet
hermeznetwork/docs pull request #45
Opened 2021-01-10 23:00 UTC by AlbertoElias

2021-01-10 23:37 UTC, druiz0992 approved these changes, later dismissed
I added a link to the sidebar

2021-01-11 09:23 UTC, jleebee requested changes

2021-01-11 09:23 UTC, jleebee commented on docs/developers/hermez-wallet.md
> +It is the first wallet to interact with the Hermez network. It supports depositing, transferring and withdrawing ETH and ERC-20 tokens in Hermez. Wallet provides a simple UI to get started.
"It is the first wallet to interact with the Hermez Network." 

"The wallet provides a simple UI to get started" 
or 
"Hermez Wallet provides a simple UI to get started."

2021-01-11 09:23 UTC, jleebee commented on docs/developers/hermez-wallet.md
> +In case of a `Transfer`, there will also be a **receiver** input. This input also supports scanning a QR code or pasting the Receiver's address directly.
"In the case of a..."

2021-01-11 09:23 UTC, jleebee commented on docs/developers/hermez-wallet.md
> +And opening a transaction shows information in regard to that transaction. There's also a button to open the Batch Explorer with all the information.
"Opening a transaction shows information related to that transaction."

2021-01-11 09:23 UTC, jleebee commented on docs/developers/hermez-wallet.md
> +## Withdraws
Withdraw or Withdrawals

2021-01-11 09:23 UTC, jleebee commented on docs/developers/hermez-wallet.md
> +They are a 2 part process. After doing the first part as explained above, a card appears in the Home or in the respective account page. When ready, it will show a button to finalise the withdrawal.
"Withdrawals are a two-part process.  After completing the first part explained above, a card appears on the Home screen or on the respective account page."

2021-01-11 10:28 UTC, AlbertoElias commented
@jleebee Thank you! Fixed!

2021-01-11 13:03 UTC, merged