update circuits to float40
hermeznetwork/docs pull request #49
Opened 2021-02-10 15:32 UTC by krlosMata

this PR updates the following:
- circuits with float40
- removes trailing spaces

2021-02-11 13:46 UTC, jleebee requested changes
Just a few edits needed :)

2021-02-11 13:46 UTC, jleebee commented on docs/developers/protocol/consensus/consensus.md
> +- The rest will will be allocated as Hermez Network usage incentives, compensating active engagement and network adoption, e.g. rewarding transaction and rewarding the holding of specific tokens in H
```suggestion
- The rest will be allocated as Hermez Network usage incentives, compensating active engagement and network adoption, e.g. rewarding transaction and rewarding the holding of specific tokens in Hermez L2 addresses, instead of on L1 Ethereum addresses.
```

2021-02-11 13:46 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/circuits/circuits.md
> +It is important to note that the templates included in this main circuit are intended to be computed in parallel. Meaning that the output of the very first transaction could be computed as it's outpu
```suggestion
It is important to note that the templates included in this main circuit are intended to be computed in parallel. Meaning that the output of the very first transaction could be computed as its output is not necessary to compute the next transaction. Then, all transactions could be computed in parallel. In order to achieve that, it is needed to supply intermediate signals to allow modules parallelization.
```

2021-02-11 13:46 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/circuits/circuits.md
> +> It should be noted that this circuit is heavily attach with the [hermez smart contract](developers/protocol/hermez-protocol/contracts/contracts?id=hermez-smart-contracts)
```suggestion
> It should be noted that this circuit is heavily attached to the [hermez smart contract](developers/protocol/hermez-protocol/contracts/contracts?id=hermez-smart-contracts)
```

2021-02-11 13:46 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/protocol.md
> +Sender sends the transaction to a Ethereum address recipient in the state tree.
```suggestion
The sender sends the transaction to an Ethereum address recipient in the state tree.
```

2021-02-11 13:46 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/protocol.md
> +If the recipient does not exist and coordinator wants to process the transaction, coordinator should create a new account with the recipient Ethereum address.
```suggestion
If the recipient does not exist and the coordinator wants to process the transaction, coordinator should create a new account with the recipient's Ethereum address.
```

2021-02-11 13:46 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/protocol.md
> +> It is important to mention that this kind of transaction allows the creation of new accounts in the state tree without the need of having any `ether` on L1. Hence, users could create new accounts a
```suggestion
> It is important to mention that this kind of transaction allows for the creation of new accounts in the state tree without needing to have any `ether` on L1. Hence, users could create new accounts and deposit tokens just through an L2 transaction.
```

2021-02-11 13:46 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/protocol.md
> +> It is important to mention that this kind of transaction allows for the creation of new accounts in the state tree without the need of having any `ether` on L1. Hence, users could create new accoun
```suggestion
> It is important to mention that this kind of transaction allows for the creation of new accounts in the state tree without needing to have any `ether` on L1. Hence, users could create new accounts and deposit tokens just through an L2 transaction.
```

2021-02-16 13:53 UTC, jleebee approved these changes

2021-02-16 16:21 UTC, jbaylina approved these changes

2021-02-16 22:25 UTC, merged