Feature/exchange flow
hermeznetwork/docs pull request #52
Opened 2021-03-12 15:51 UTC by druiz0992

2021-03-14 21:31 UTC, jleebee requested changes

2021-03-14 21:31 UTC, jleebee commented on docs/users/exchanges.md
> +-  User has an Hermez account (`HEZUser-ETH`)
```suggestion
-  User has a Hermez account (`HEZUser-ETH`)
```

2021-03-14 21:31 UTC, jleebee commented on docs/users/exchanges.md
> +and thus the creation is really cheap. Once the user has received the L2 account address, he can perform the transfer normally.
```suggestion
and thus the creation is very inexpensive. Once the user has received the L2 account address, he can perform the transfer normally.
```

2021-03-14 21:31 UTC, jleebee commented on docs/users/exchanges.md
> +1. User requests to do a transfer to the exchange from his Hermez account using some front-end.
Please discard if this isn't the correct terminology for this instance:
"1. User requests to do a transfer to the exchange from his Hermez account using a front-end framework."

2021-03-14 21:31 UTC, jleebee commented on docs/users/exchanges.md
> +2. Exchange creates an L2 (internal) account on behalf of the user (`L2ExUser-ETH`) and provides the address via a front-end. This account is controlled by the exchange.
```suggestion
2. Exchange creates an L2 (internal) account on behalf of the user (`L2ExUser-ETH`) and provides the address via front-end framework. This account is controlled by the exchange. 
```

2021-03-14 21:31 UTC, jleebee commented on docs/users/exchanges.md
> +4. Exchange monitors balance of the account `L2ExUser-ETH`, and once transfer has completed, exchange performs transfer from `L2ExUser-ETH` to `L2Ex-ETH` for 10 ETH.
```suggestion
4. Exchange monitors balance of the account `L2ExUser-ETH`, and once transfer is complete, exchange performs transfer from `L2ExUser-ETH` to `L2Ex-ETH` for 10 ETH.
```

2021-03-14 21:31 UTC, jleebee commented on docs/users/exchanges.md
> +  // - the following code could be done through the web wallet provided by hermez network
```suggestion
  // - the following code could be done through the web wallet provided by Hermez Network
```

2021-03-14 21:31 UTC, jleebee commented on docs/users/exchanges.md
> +  // - it is assumed that the user has already ether in hermez network
```suggestion
  // - it is assumed that the user has already Ether in Hermez Network
```

2021-03-16 12:29 UTC, jbaylina approved these changes, later dismissed

2021-03-17 14:28 UTC, krlosMata requested changes

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +-  Exchange already has some Hermez accounts for each trading token (`HEZEx-ETH`, `HEZEx-DAI`,...).
it could be useful to add link here to "how to create accounts" documentation

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +Both exchange and user p pre-existing accounts are regular Hermez accounts, consisting of an L2 account linked to an Ethereum account where funds can be withdrawn.
```suggestion
Both exchange and user pre-existing accounts are regular Hermez accounts, consisting of an L2 account linked to an Ethereum account where funds can be withdrawn.
```

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +The following is an example of code used to initialize hermezjs` with `Hermez testnet` deployment and create both user and exchange accounts. You need to supply your
```suggestion
The following is an example of code used to initialize hermezjs with `Hermez testnet` deployment and create both user and exchange accounts. You need to supply your
```

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +own WEB3_URL (Ethereum Node URL) and two Rinkeby Ethereum Provate Keys.
```suggestion
own WEB3_URL (Ethereum Node URL) and two Rinkeby Ethereum Private Keys.
```

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +  const tokenERC20 = token.tokens[tokenIndex];
Token index 0 is `ether`. I may be useful to change this name to `tokenEth` or just a better appropriate name

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +  console.log("W2", wallet2)
I would remove this `console.log`

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +-  User has a Hermez account (`HEZUser-ETH`)
```suggestion
-  User has an Hermez account (`HEZUser-ETH`)
```

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +  const infoAccountExchange = (await hermez.CoordinatorAPI.getAccounts(hermezExchangeWallet.hermezEthereumAddress, [tokenERC20.id]))
It could be useful to add a `console.log("infoAccountExchange: ", infoAccountExchange)` here.
Otherwise, I would remove this line since it is not used

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +## User Transfers Tokens to Exchange
Title `User Transfers Tokens to Exchange` is not shown properly when rendering hackmd in web. Seems that title is too large for content search panel on the right side. I would suggest to change the name for a shorter one such as `Deposit to exchange`

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +The creation of this user account by the exchange is only done once.
It is done once per user and token id. Or it could not be done once.
Exchange could provide different addresses for the same user-tokenId. I think it would depend exclusively on exchange decision.
I would remove this sentence

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +  // Transfer funds to main exchange account
The following code is rendered well in web.
Delete one line and it will be rendered properly

2021-03-17 14:28 UTC, krlosMata commented on docs/users/exchanges.md
> +const EXAMPLES_WEB3_URL = "http://----";
In section `pre-requisites`, those variables are empty.
I would either change `pre-requisites` section or this one in order to match them

2021-03-17 18:17 UTC, merged