fix some doc typos
hermeznetwork/docs pull request #59
Opened 2021-04-05 17:18 UTC by Pantani

2021-04-06 07:14 UTC, krlosMata submitted a review, later dismissed
:smile_cat:

2021-04-06 08:42 UTC, jleebee commented on docs/about/model.md
> +The auction process incentivizes efficiency, as coordinators need to include as many transactions as possible in each time slot to compensate for their bidding costs and operative expenses.
DS mentioned he wanted to use British spelling, so we could keep it "incentivises"

2021-04-06 08:43 UTC, jleebee commented on docs/about/model.md
> +Also, governance will be able to implement the effective decentralization of the network by locking the price of specific slots of the auction to 0 HEZ and therefore wouldn't require any minimum bid,
Same as above, we can keep the spelling with 's' for the British spelling.

2021-04-06 08:45 UTC, jleebee commented on docs/about/scalability.md
> +Trust-minimized blockchain scaling mechanisms are sorely needed if blockchain applications are ever to achieve mass adoption.
"minimised" for British spelling

2021-04-06 09:44 UTC, jleebee requested changes

2021-04-06 09:44 UTC, jleebee commented on docs/developers/glossary.md
> +Selection of coordinator is done via an auction process managed by a smart contract. The node with the highest bid in an open slot will earn the right to forge new batches and collect the fees from t
```suggestion
Selection of the coordinator is done via an auction process managed by a smart contract. The node with the highest bid in an open slot will earn the right to forge new batches and collect the fees from the transactions included in the batch. This auction is the process by which Hermez Network reaches a consensus on which node shall play the role of coordinator in an upcoming slot.
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/glossary.md
> +Hermez provides the capability that some transactions to be processed together. This feature is called Atomic Transactions.
```suggestion
Hermez provides the capability for some transactions to be processed together. This feature is called Atomic Transactions.
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/glossary.md
>  Hermez uses Sparse Merkle Trees to store the state of the Hermez network. There are two main tree structures:
```suggestion
Hermez uses Sparse Merkle Trees to store the state of the Hermez Network. There are two main tree structures:
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/glossary.md
>  User needs to prove that it owns a leaf in the exit tree in order to perform a withdrawal and get the tokens back. This verification could be done either by submitting a merkle tree proof or by submi
```suggestion
User needs to prove that it owns a leaf in the exit tree in order to perform a withdrawal and get the tokens back. This verification could be done either by submitting a Merkle tree proof or by submitting a zkProof. 
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/glossary.md
> +In order to transfer funds from L2 account to ethereum account two separate transactions are invoked. The first transaction is Exit, where funds are transferred to a smart contract. The second transa
```suggestion
In order to transfer funds from the L2 account to the Ethereum account, two separate transactions are invoked. The first transaction is Exit, where funds are transferred to a smart contract. The second transaction is Withdrawal. If conditions are met, Withdrawal can be instant. If funds to be withdrawn exceed certain limits, the Withdrawal is delayed until the transaction is cleared.
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/protocol/consensus/consensus.md
> +This element has the mission to support the network bootstrap and at some moment will disappear if the network gets traction. This event of the boot coordinator disappearing will be a governance deci
```suggestion
This element has the mission to support the network bootstrap and at some moment will disappear when the network gains traction. Removal of the boot coordinator will be a governance decision.
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/protocol/consensus/consensus.md
> +Basically, its role is to forge any slot where there are no winner in the auction without the need to make a bid.
```suggestion
Basically, its role is to forge any slot where there is no winner in the auction without the need to make a bid.
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/contracts/contracts.md
>    - Set a new state merkle root and exit merkle root
```suggestion
  - Set a new state Merkle root and exit Merkle root
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/protocol.md
>  funds back from smart contract to Ethereum address. This is done by
```suggestion
funds back from the smart contract to Ethereum address. This is done by
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/protocol.md
> +Fees are paid on L2 transactions in the same token that they are done. So, if the user sends a token A, the fees will be paid in token A.
```suggestion
Fees are paid on L2 transactions in the same token that they are done. So, if the user sends "Token A", the fees will be paid in "Token A".
```

2021-04-06 09:44 UTC, jleebee commented on docs/faq/coordinators.md
> +They make benefit from these fees minus the operational costs and the bid price for the slot.
```suggestion
They profit from these fees minus the operational costs and the bid price for the slot.
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/protocol/consensus/consensus.md
>  The general purpose of this protocol is to describe the rules to coordinate this auction where the bids will be placed only in HEZ utility token.
```suggestion
The general purpose of this protocol is to describe the rules to coordinate the auction where the bids will be placed only in HEZ utility token.
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/protocol/consensus/consensus.md
> +- Incentivize coordinators to participate in ZK-Rollup
```suggestion
- Incentivize coordinators to participate in the ZK-Rollup
```

2021-04-06 09:44 UTC, jleebee commented on docs/developers/protocol/hermez-protocol/contracts/contracts.md
> +This logic is implemented during the bootstrapping phase of the network as an additional security measure in order to mitigate attacks that could potentially provide illegitimate access to user funds
```suggestion
This logic is implemented during the bootstrapping phase of the network as an additional security measure to mitigate attacks that could potentially provide illegitimate access to user funds from Hermez Network. The objective is to temporarily enable this last-resort measure while preserving decentralization.
```

2021-04-07 07:49 UTC, jleebee reviewed
I found a few more things to edit : )

2021-04-07 07:49 UTC, jleebee commented on docs/developers/glossary.md
> +Transactions is the generic name given to every operation in the Hermez Network. Transactions may be initiated by a user or by the coordinator. Transactions may also happen at L1 or L2. The coordinat
```suggestion
Transactions is the generic name given to every operation in the Hermez Network. Transactions may be initiated by a user or by the coordinator. Transactions may also happen on L1 or L2. The coordinator node is in charge of collecting and processing transactions in batches generating a ZK-SNARK to prove that the transactions have been carried out according to some rules.
```

2021-04-07 07:49 UTC, jleebee commented on docs/developers/glossary.md
> +The Hermez Network community intends to follow a strategy of “Governance minimization”. This model is intended to be a initially a bootstrap governance mechanism to adjust and manage some network par
```suggestion
The Hermez Network community intends to follow a strategy of “Governance minimization”. This model is intended to initially be a bootstrap governance mechanism to adjust and manage some network parameters mainly for security and stability purposes until the network reaches a sufficient degree of maturity to become fully decentralized; at that stage, the initial bootstrap Governance model will no longer be necessary and will eventually disappear.
```

2021-04-07 07:49 UTC, jleebee commented on docs/about/scalability.md
>  During the last year, it has become clear that rollups will be the dominant scaling paradigm on the Ethereum public blockchain: with this in mind, Iden3 has developed and is preparing to launch Herme
Should we edit this intro, since the network has launched? 

"Iden3 has developed and recently launched Hermez...." 
```suggestion
During the last year, it has become clear that rollups will be the dominant scaling paradigm on the Ethereum public blockchain: with this in mind, Iden3 has developed and is preparing to launch Hermez, a **ZK-Rollup** focused on scaling payments and token transfers on Ethereum.
```
```suggestion
During the last year, it has become clear that rollups will be the dominant scaling paradigm on the Ethereum public blockchain: with this in mind, Iden3 has developed and recently launched Hermez, a **ZK-Rollup** focused on scaling payments and token transfers on Ethereum.
```

2021-04-07 07:49 UTC, jleebee commented on docs/developers/protocol/consensus/consensus.md
> +A bid will not pay the premium on top of the previous bid, but a bid placed in the auction should be at least **1.1 times** (system parameter) the previous bid or over the minimal bidding price (if i
```suggestion
A bid will not pay a premium on top of the previous bid, but a bid placed in the auction should be at least **1.1 times** (system parameter) the previous bid or over the minimum bidding price (if it's the first one) to be accepted as valid.
```

2021-04-07 07:49 UTC, jleebee commented on docs/developers/protocol/consensus/consensus.md
> +Auction will be structured in series of 6 slots `slots[5]`, with **10 HEZ** as initial minimal bidding price for all the slots. The governance can change this value `slots[i]` independently at any ti
```suggestion
Auction will be structured in series of 6 slots `slots[5]`, with **10 HEZ** as initial minimal bidding price for all the slots. The governance can change this value `slots[i]` independently at any time and **affecting open auctions**, in such a way that all the slots whose `slot % 6 = i` will have the same minimum bid. Bids under the new minimal bidding price will not be considered as valid bids anymore and bidders (if no new bids outbid theirs) will be sent back their HEZ in the event that the slot is fully processed (forge).
```

2021-04-07 07:49 UTC, jleebee commented on docs/introduction/glossary.md
> +The Hermez Network community intends to follow a strategy of “Governance minimization”. This model is intended to be a initially a bootstrap governance mechanism to adjust and manage some network par
```suggestion
The Hermez Network community intends to follow a strategy of “Governance minimization”. This model initially intends to be a bootstrap governance mechanism to adjust and manage some network parameters mainly for security and stability purposes until the network reaches a sufficient degree of maturity to become fully decentralized; at that stage, the initial bootstrap Governance model will no longer be necessary and will eventually disappear.
```

2021-04-07 19:26 UTC, Pantani commented on docs/about/scalability.md
>  During the last year, it has become clear that rollups will be the dominant scaling paradigm on the Ethereum public blockchain: with this in mind, Iden3 has developed and is preparing to launch Herme
I agree!!

2021-04-07 19:37 UTC, jleebee submitted a review, later dismissed

2021-04-07 19:59 UTC, jleebee submitted a review, later dismissed

2021-04-08 07:47 UTC, jleebee approved these changes

2021-04-08 21:14 UTC, krlosMata approved these changes
:smile_cat:

2021-04-08 21:14 UTC, merged