First version
hermeznetwork/docs pull request #69
Opened 2021-04-29 09:31 UTC by druiz0992

2021-04-29 13:39 UTC, jleebee requested changes
A few edits, I couldn't think of any additional questions.  However, you had mentioned that you had many questions to clarify the nonce, do we need to add anything about that here?

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +This FAQ is addressed to developers integrating Hermez Network into their service, such es exchanges.
```suggestion
This FAQ is addressed to developers integrating Hermez Network into their service, such as exchanges.
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +First plance to start is the [Developer Guide](../developers/dev-guide.md) that provides an introduction to Hermez and the protocol. Additionally, there are some
```suggestion
The first place to start is the [Developer Guide](../developers/dev-guide.md) that provides an introduction to Hermez and the protocol. Additionally, there are some 
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +Additionally, there are some examples on how to interact with Hermez written in golang. You can find these examples [here](https://github.com/hermeznetwork/hermez-integration)
```suggestion
Additionally, there are some examples of how to interact with Hermez written in Golang. You can find these examples [here](https://github.com/hermeznetwork/hermez-integration)
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +An account in Hermez is represented by a leave in the Merkle tree. Each account can only store one token type. There are two account types:
```suggestion
An account in Hermez is represented by a leaf in the Merkle tree. Each account can only store one token type. There are two account types:
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +- Normal accounts include a hezEthereum and a Baby Jubjub address. These accounts can be used to do deposits from L1, transfers within L2 and withdraws to L1.
```suggestion
- Normal accounts include a hezEthereum and a Baby Jubjub address. These accounts can be used to perform deposits from L1, transfers within L2, and withdrawals to L1.
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +- Internal accounts include only a Baby Jubjub address. These accounts can be only be used to do transfers within L2.
```suggestion
- Internal accounts only include a Baby Jubjub address and can only be used to do transfers within L2.
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +You don't, unless you want to. However, as an integrator offering some service on top of Hermez Network you may want to spin a Hermez node in synchronizer mode to access
```suggestion
You don't unless you want to. However, as an integrator offering some service on top of Hermez Network, you may want to spin a Hermez node in synchronizer mode to access the Hermez data directly without any intermediary. 
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +the Hermez data directly without any intermediary.
```suggestion

```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +Whenever you send a L2 transaction to Hermez, it will be added to a transaction-pool queue. This transaction will remain there until it has been processed or expired. The possible states of a transac
```suggestion
Whenever you send an L2 transaction to Hermez, it will be added to a transaction-pool queue. This transaction will remain there until it has been processed or expires. The possible states of a transaction in the 
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +transaction pool include `forged`, `forging`, `pending` and `invalid`.To check the status of a transaction, you can query the API using the returned transaction id by seding a GET /transactions-pool/
```suggestion
transaction pool include `forged`, `forging`, `pending` and `invalid`.To check the status of a transaction, you can query the API using the returned transaction id by sending a GET /transactions-pool/{transaction-id}. 
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +A valid transaction should always be processed within 15 minutes. Reasons why a transaction may be invalid and not processed by any Coordinator include insufficient balance in the sender account, une
```suggestion
A valid transaction should always be processed within 15 minutes. There are several reasons why a transaction may be invalid and therefore not processed by any Coordinator; insufficient balance in the sender account, nonexistent sender account,
```

2021-04-29 13:39 UTC, jleebee commented on docs/faq/integrators.md
> +### Where can I submit a bug report or need help?
```suggestion
### Where can I submit a bug report or contact Hermez for additional help?
```

2021-04-29 17:39 UTC, druiz0992 commented on docs/faq/integrators.md
> +the Hermez data directly without any intermediary.
Do you want me to remove the line `the Hermez data directly without any intermediary`?

2021-04-30 06:59 UTC, jleebee commented on docs/faq/integrators.md
> +You don't, unless you want to. However, as an integrator offering some service on top of Hermez Network you may want to spin a Hermez node in synchronizer mode to access
I moved the line "the Hermez data directly without any intermediary."  here to correct the spacing

2021-04-30 07:00 UTC, jleebee commented on docs/faq/integrators.md
> +the Hermez data directly without any intermediary.
I suggested an edit above it & included that sentence there since it was spaced in an odd way (the space between "access" and "the Hermez data".

2021-05-03 09:01 UTC, jleebee requested changes
a few edits :)

2021-05-03 09:01 UTC, jleebee commented on docs/faq/integrators.md
> +You don't, unless you want to. However, as an integrator offering some service on top of Hermez Network you may want to spin a Hermez node in synchronizer mode to access the Hermez data directly with
```suggestion
You don't unless you want to. However, as an integrator offering some service on top of Hermez Network, you may want to spin a Hermez node in synchronizer mode to directly access the Hermez data without an intermediary. 
```

2021-05-03 09:01 UTC, jleebee commented on docs/faq/integrators.md
> +Whenever you send a L2 transaction to Hermez, it will be added to a transaction-pool queue. This transaction will remain there until it has been processed or expires. The possible states of a transac
```suggestion
Whenever you send an L2 transaction to Hermez, it will be added to a transaction-pool queue. This transaction will remain there until it has been processed or expires. The possible states of a transaction in the 
```

2021-05-03 09:01 UTC, jleebee commented on docs/faq/integrators.md
> +### Why a transaction may not be processed?
```suggestion
### What are the reasons a transaction may not be processed?
```

2021-05-03 09:01 UTC, jleebee commented on docs/faq/integrators.md
> +### Can I cancel a transction in the pool?
```suggestion
### Can I cancel a transaction in the pool?
```

2021-05-03 09:01 UTC, jleebee commented on docs/faq/integrators.md
> +Coordinators select the recommended fee depending on the different transaction types. These fees can be querired in the `/state` endpoint and are in USD. There are three types of fees:
```suggestion
Coordinators select the recommended fee depending on the different transaction types. These fees can be queried in the `/state` endpoint and are in USD. There are three types of fees:
```

2021-05-03 09:01 UTC, jleebee commented on docs/faq/integrators.md
> +As always, please report bugs to hello@hermez.network. Also, you can always contact us in [Discord](https://bit.ly/hermez-discord). You can also find more information in the [Hermez documentation pag
```suggestion
As always, please report bugs to hello@hermez.network. Additionally, you can always contact us in [Discord](https://bit.ly/hermez-discord). You can also find more information in the [Hermez documentation page](https://docs.hermez.io)
```

2021-05-05 14:43 UTC, jleebee requested changes
Just a few little things, everything else looks great : )

2021-05-05 14:43 UTC, jleebee commented on docs/faq/integrators.md
> +You don't, unless you want to. However, as an integrator offering some service on top of Hermez Network you may want to spin a Hermez node in synchronizer mode to directly access the Hermez data dire
```suggestion
You don't unless you want to. However, as an integrator offering some service on top of Hermez Network, you may want to spin a Hermez node in synchronizer mode to directly access the Hermez data directly without an intermediary. 
```

2021-05-05 14:43 UTC, jleebee commented on docs/faq/integrators.md
> +A valid transaction should always be processed within 15 minutes. There are several reasons why a transaction may be invalid and therefore not processed by any Coordinator; insufficient balance in th
```suggestion
A valid transaction should always be processed within 15 minutes. There are several reasons why a transaction may be invalid and therefore not processed by any Coordinator; insufficient balance in the sender account, nonexistent sender account, destination account hasn't given permission to create an account, fees lower than suggested Coordinator fees,... Checking the transaction status will provide some feedback on the reason why the transaction wasn't forged.
```

2021-05-13 09:40 UTC, merged